spring.application.name=nasorchestrator

server.port=8081
management.endpoints.web.exposure.include=mappings

truenas.base-url=http://10.184.211.79
truenas.api-key=1-dcAO8W9KPYQ0m1vEfh6l0lg9JPBCWSixUtJB70Pi4AG35oV41lR4Z7USdLoD3hqN

smb.username=antar
smb.password=antar_admin
smb.share-base-url=smb://10.184.211.79/antar-share/

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

smb.bootstrap.enabled=true
smb.bootstrap.pool-name=antarpool
smb.bootstrap.disk-identifier=nvme0n2
smb.bootstrap.dataset-name=antar-dataset
smb.bootstrap.share-name=antar-share