spring:
  application:
    name: streaming-service
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: streaming-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: com.tamojit.streamingservice.event.VideoEncodedEvent

server:
  port: 8084

nas:
  orchestrator:
    base-url: http://nas-orchestrator:8081

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5501}

management:
  endpoints:
    web:
      exposure:
        include: health, info