spring.application.name=nasorchestrator

server.port=8081
management.endpoints.web.exposure.include=mappings

truenas.base-url=${TRUENAS_BASE_URL}
truenas.api-key=${TRUENAS_API_KEY}

smb.full-name=ANTAR Orchestrator Account
smb.username=${SMB_USERNAME}
smb.password=${SMB_PASSWORD}
smb.share-base-url=${SMB_SHARE_BASE_URL}

spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

smb.bootstrap.enabled=${SMB_BOOTSTRAP_ENABLED:true}
smb.bootstrap.pool-name=antarpool
smb.bootstrap.disk-identifier=${SMB_BOOTSTRAP_DISK_IDENTIFIER}
smb.bootstrap.dataset-name=antar-dataset
smb.bootstrap.share-name=antar-share

cache.l1.max-weight-bytes=268435456
cache.l2.enabled=true
spring.data.redis.host=localhost
spring.data.redis.port=6379